image: node:latest

cache:
  paths:
    - node_modules/

make_code_nice:
  tags: 
    - docker
  script:
    - npm install
    - npm run format

check_if_code_is_nice:
  tags: 
    - docker
  script:
  - npm install
  - npm run lint
